branches:
  only:
  - master

language: java

jdk:
  - openjdk11

os: linux

arch:
  - s390x
  - ppc64le

script:
#  - sudo apt-get install -y openjdk-11-jdk;
#  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-s390x && export PATH=$JAVA_HOME/bin:$PATH;
  - ./sbt test
